# Generated by Django 4.2.1 on 2023-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminsignin',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobileno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=46)),
                ('cookiekey', models.CharField(default='0', max_length=45)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
