# Generated by Django 4.2.1 on 2023-05-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminsignin',
            new_name='admindetails',
        ),
    ]
