# Generated by Django 4.2.1 on 2023-05-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_rename_adminsignin_admindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='EntryDateTime'),
        ),
    ]
