# Generated by Django 4.2.2 on 2023-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_alter_admindetails_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='secretcode',
            field=models.CharField(default='devrev', max_length=20),
            preserve_default=False,
        ),
    ]
