# Generated by Django 4.2.2 on 2023-06-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_admindetails_secretcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetails',
            name='secretcode',
        ),
    ]
