# Generated by Django 4.2.1 on 2023-05-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('bloodgroup', models.CharField(max_length=3)),
                ('doorno', models.CharField(blank=True, max_length=6, null=True)),
                ('line1', models.CharField(blank=True, max_length=50, null=True)),
                ('line2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
