# Generated by Django 4.2.1 on 2023-05-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignin',
            name='cookiekey',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
