# Generated by Django 4.2.1 on 2023-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersignin_cookiekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignin',
            name='id',
        ),
        migrations.AlterField(
            model_name='usersignin',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
