# Generated by Django 4.2.1 on 2023-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usersignin_id_alter_usersignin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignin',
            name='password',
            field=models.CharField(max_length=46),
        ),
    ]
