# Generated by Django 4.2.1 on 2023-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usersignin_cookiekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignin',
            name='mobileno',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersignin',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
