# Generated by Django 4.2.2 on 2023-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usersignin_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usersignin',
            name='doorno',
        ),
        migrations.RemoveField(
            model_name='usersignin',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='usersignin',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='usersignin',
            name='pincode',
        ),
        migrations.AddField(
            model_name='usersignin',
            name='email',
            field=models.EmailField(default='201501002@rajalakshmi.edu.in', max_length=254),
            preserve_default=False,
        ),
    ]
