# Generated by Django 4.2.2 on 2023-06-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
