# Generated by Django 4.2.2 on 2023-06-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_msg_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='userid',
        ),
        migrations.AddField(
            model_name='msg',
            name='users',
            field=models.ManyToManyField(related_name='messages', to='user.usersignin'),
        ),
    ]
