# Generated by Django 4.2.2 on 2023-06-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_msg_userid_msg_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='msg',
            new_name='message',
        ),
    ]
