# Generated by Django 4.2.2 on 2023-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_message_entrydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sub',
            field=models.TextField(null=True),
        ),
    ]
