# Generated by Django 4.2.2 on 2023-06-14 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_message_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='entrydate',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sub',
        ),
        migrations.AddField(
            model_name='message',
            name='entrydatetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
