# Generated by Django 4.2.1 on 2023-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersdb',
            name='name',
            field=models.CharField(default='xxx clinic', max_length=50),
            preserve_default=False,
        ),
    ]
