# Generated by Django 4.2.1 on 2023-05-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usersignin_id_alter_usersignin_name'),
        ('centers', '0002_centersdb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydatetime', models.DateTimeField(auto_now_add=True)),
                ('centerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.centersdb')),
                ('userno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usersignin')),
            ],
        ),
    ]
