# Generated by Django 4.2.1 on 2023-05-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='userno',
        ),
    ]
