# Generated by Django 4.2.1 on 2023-05-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_entries_userno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centersdb',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='EntryDateTime'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='entrydatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='EntryDateTime'),
        ),
    ]
