# Generated by Django 4.2.2 on 2023-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_centersdb_slot1_centersdb_slot2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='slot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
