# Generated by Django 4.2.2 on 2023-06-10 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_entries_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='entrydatetime',
        ),
        migrations.AddField(
            model_name='entries',
            name='entrydate',
            field=models.DateField(default=datetime.date.today, verbose_name='EntryDate'),
        ),
    ]
