# Generated by Django 4.2.2 on 2023-06-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_remove_entries_entrydatetime_entries_entrydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centersdb',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='EntryDate'),
        ),
    ]
