# Generated by Django 4.2.2 on 2023-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_alter_centersdb_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centersdb',
            name='slot1',
        ),
        migrations.RemoveField(
            model_name='centersdb',
            name='slot2',
        ),
        migrations.AddField(
            model_name='centersdb',
            name='dosage',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centersdb',
            name='slots',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centersdb',
            name='vacancy',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
