# Generated by Django 4.2.2 on 2023-06-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_remove_centersdb_slot1_remove_centersdb_slot2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entries',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
