# Generated by Django 4.2.2 on 2023-06-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_entries_is_expired_entries_is_vaccinated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='is_expired',
        ),
    ]
