# Generated by Django 4.2.2 on 2023-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0013_remove_entries_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='age',
            field=models.CharField(default=18, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='bloodgroup',
            field=models.CharField(default='o+', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='mobileno',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
