# Generated by Django 4.2.4 on 2023-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0014_entries_age_entries_bloodgroup_entries_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='qr_code',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
