# Generated by Django 4.2.4 on 2023-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0015_entries_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_codes'),
        ),
    ]
