# Generated by Django 4.2.4 on 2023-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0016_alter_entries_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='certificate',
            field=models.ImageField(null=True, upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_codes/'),
        ),
    ]
